# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Rails:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 128

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Rails/HasAndBelongsToMany:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false


Style/SpaceBeforeFirstArg:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

